--- a/.github/workflows/windows.yaml
+++ b/.github/workflows/windows.yaml
@@ -15,11 +15,12 @@
     name: ci (go:${{ matrix.go-version.name }})
     runs-on: windows-latest
     strategy:
-      go-version:
-        - name: latest
-          version: 1.24.x
-        - name: previous
-          version: 1.23.x
+      matrix:
+        go-version:
+          - name: latest
+            version: 1.24.x
+          - name: previous
+            version: 1.23.x
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
@@ -33,4 +34,4 @@
         shell: bash
         run: |
           go build ./...
-          go test -vet=off -race ./...
+          go test -vet=off -race ./...